### ISSUE TITLE
Android 11 Update

### ISSUE THREAD

**Issue by Julienraptor01** [Raerten/HSAccs#2]
Hello, do you have planned to release a version compatible with Android 11.
Your app is quite useful but my phone was broken and now i've a new phone that is sadly incompatible for now.

**Comment by Raerten** [comment]
hi, android 11 imposes strict restrictions on working with the file system and the implementation of the functionality has become difficult, so I do not plan to develop this program further

**Comment by Julienraptor01** [comment]
Ok then i'm gonna close this thread.
